name: CI

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '20' ]
    steps:
      - uses: actions/checkout@v1
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Jalankan Skrip
        env:
          SUPER_SECRET: ${{ secrets.SUPER_SECRET }}
        run: |
          npm install -g lighthouse
          lighthouse https://www.oxyplug.com/
