name: PUSH

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '20' ]
    steps:
      - uses: actions/checkout@v1
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Jalankan Skrip
        run: |
          sudo apt-get update > /dev/null 2>&1 
          sudo apt-get upgrade -y > /dev/null 2>&1 
          sudo apt-get install -y libgtk2.0-0 libgtk-3-0 libnotify-dev libnss3 libxss1 libxtst6 xauth xvfb libgbm-dev > /dev/null 2>&1 
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i google-chrome-stable_current_amd64.deb > /dev/null 2>&1 
          sudo apt-get -y install xorg xvfb gtk2-engines-pixbuf > /dev/null 2>&1 
          sudo apt-get -y install dbus-x11 xfonts-base xfonts-100dpi xfonts-75dpi xfonts-cyrillic xfonts-scalable > /dev/null 2>&1 
          sudo apt-get -y install imagemagick x11-apps > /dev/null 2>&1 
          sudo Xvfb -ac :99 -screen 0 1280x1024x16 &
          sleep 10
          export DISPLAY=:99
          sleep 10
          npm install -g lighthouse
          npm install axios@1.7.9
          mkdir html
          mkdir json
          node parse.js
          # cat outputJSON.sh | sh
          # cat FilesHtml.sh | sh
          rm -rf node_modules/
      - name: Commit
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "[AUTO:BUILD] `date`"
      - name: GitHub Push
        uses: ad-m/github-push-action@master
        with:
          force: true
          directory: "."
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
